# Generated by Django 3.2.6 on 2021-08-12 10:28

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(upload_to='avatars/%Y/%m')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BangGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giaVe', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ChuyenXe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoiDiemKH', models.DateTimeField()),
                ('thoiGianHT', models.TimeField()),
                ('trangThai', models.BooleanField(default=True)),
                ('maTaiXe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CX_maTaiXe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiaDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenDiaDiem', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ghe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenGhe', models.CharField(max_length=4, unique=True)),
                ('trangThai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HinhThucTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenHT', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiXe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenLoaiXe', models.CharField(max_length=100)),
                ('soGhe', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Xe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soXe', models.CharField(max_length=6, unique=True)),
                ('tenLoaiXe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Xe_tenLoaiXe', to='quanly.loaixe')),
            ],
        ),
        migrations.CreateModel(
            name='TuyenXe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaDiemDen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TX_diaDiemDen', to='quanly.diadiem')),
                ('diaDiemDi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TX_diaDiemDi', to='quanly.diadiem')),
            ],
        ),
        migrations.CreateModel(
            name='PhanHoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noiDung', models.TextField()),
                ('thoiGianTao', models.DateTimeField(auto_now_add=True)),
                ('thoiGianCS', models.DateTimeField(auto_now=True)),
                ('maChuyenXe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PH_maChuyenXe', to='quanly.chuyenxe')),
                ('maKhachHang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PH_maKH', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayThanhToan', models.DateTimeField(auto_now_add=True)),
                ('tongTien', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('hinhThuc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HD_hinhThuc', to='quanly.hinhthuctt')),
                ('maKhachHang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HD_maKH', to=settings.AUTH_USER_MODEL)),
                ('maNhanVien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HD_maNV', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chuyenxe',
            name='soXe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CX_soXe', to='quanly.xe'),
        ),
        migrations.AddField(
            model_name='chuyenxe',
            name='tuyenXe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CX_tuyenXe', to='quanly.tuyenxe'),
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maChuyenXe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CTHD_maChuyenXe', to='quanly.chuyenxe')),
                ('maGhe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CTHD_maGhe', to='quanly.ghe')),
                ('maGia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CTHD_maGia', to='quanly.banggia')),
                ('maHoaDon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CTHD_maHoaDon', to='quanly.hoadon')),
            ],
        ),
        migrations.AddField(
            model_name='banggia',
            name='loaiXe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BG_loaiXe', to='quanly.loaixe'),
        ),
        migrations.AddField(
            model_name='banggia',
            name='tuyenXe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BG_tuyenXe', to='quanly.tuyenxe'),
        ),
    ]
